SELECT 
    e1.DEPTNO,
    e1.ENAME,
    e1.HIREDATE
FROM 
    EMP e1
WHERE 
    e1.HIREDATE = (
        SELECT MAX(e2.HIREDATE)
        FROM EMP e2
        WHERE e2.DEPTNO = e1.DEPTNO
    )
ORDER BY 
    e1.HIREDATE;